#%RAML 0.8
title: Book Store API
version: 1.0
#baseUri: http://localhost:8081/api
baseUri: https://mocksvc.mulesoft.com/mocks/161647e9-c910-4c8a-96c4-8cf588e869f8/api
/books:
  get:
    headers: 
      User:
        required: true
    description: List all books, optionally filtered by a query string
    queryParameters:  
      title:
        description: An optional search query to filter the results
        example: Don Quijote de la Mancha
        required: false
    responses:
      200:
        body:
          application/json:
            example: |
              [{
              "id":"1",
              "title": "La conjura de los necios",
              "author": "John Kennedy Toole",
              "pages" : 344
              },
              {
              "id":"2",
              "title": "Sin noticias de Gurb",
              "author": "Eduardo Mendoza",
              "pages" : 523
              },
              {
                "id":"3",
                "title": "El mundo ha vivido equivocado",
                "author": "Roberto Fontanarrosa",
                "pages" : 343
              }]
              
  post:
    description: Create a new book
    headers: 
      User:
        required: true
    body:
      application/json:
        example: |
          {
            "title": "Don Quijote de la Mancha  ",
            "author": "Miguel de Cervantes",
            "pages" : 744
          }
    responses:
      201:
        description: Book successfully created.
      409:
        description: Book already exists. 
  /{id}:
    description: Get a book identify by its id.
    uriParameters: 
      id:
        required: true
    get:
      description: Get a book by id.
      headers: 
        User:
          required: true
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                "id":"3",
                "title": "El mundo ha vivido equivocado",
                "author": "Roberto Fontanarrosa",
                "pages" : 343
                }
    put:
      description: Update a book
      headers: 
        User:
          required: true
      body: 
        application/json:
          example: |
            {
              "id":"1",
              "title": "La conjura de los necios",
              "author": "John Kennedy Toole",
              "pages" : 344
            }
      responses: 
        200:
          description: Book successfully updated.
        404:
          description: Book id not found.
    delete:
      description: Delete a book 
      headers: 
        User:
          required: true 
      responses: 
        204:
          description: Book succesfully removed.
        404:
          description: Book id not found.
          
          
            
                
        
        
          
              
              
            